default:
	python arrange.py --tilesfile tiles.json --ntiles=2
	python arrange.py --tilesfile tiles.json --ntiles=3
	python arrange.py --tilesfile tiles.json --ntiles=4
	python arrange.py --tilesfile tiles.json --ntiles=5
	python arrange.py --tilesfile tiles.json --ntiles=6
	python arrange.py --tilesfile tiles.json --ntiles=7

deps:
	pip install -r req.txt || uv pip install -r req.txt
	
